@GasesIndustriales.Api_HostAddress = http://localhost:5133

GET {{GasesIndustriales.Api_HostAddress}}/api/clientes
Accept: application/json

###

GET {{GasesIndustriales.Api_HostAddress}}/api/clientes/1
Accept: application/json

###

POST {{GasesIndustriales.Api_HostAddress}}/api/clientes
Content-Type: application/json

{
  "razonSocial": "Nuevo Cliente Demo SAC",
  "ruc": "20111111111",
  "telefono": "999888777",
  "direccion": "Arequipa",
  "idZona": 1,
  "tipoCliente": "NUEVO",
  "requiereGarantia": true
}

###

PUT {{GasesIndustriales.Api_HostAddress}}/api/clientes/1
Content-Type: application/json

{
  "razonSocial": "Cliente Demo Industrial SAC",
  "ruc": "20123456789",
  "telefono": "999111222",
  "direccion": "Av. Industrial 123",
  "idZona": 1,
  "tipoCliente": "FRECUENTE",
  "requiereGarantia": false,
  "activo": true
}

###

DELETE {{GasesIndustriales.Api_HostAddress}}/api/clientes/1
Accept: application/json

###

GET {{GasesIndustriales.Api_HostAddress}}/api/productos
Accept: application/json

###

GET {{GasesIndustriales.Api_HostAddress}}/api/productos/1
Accept: application/json

###

POST {{GasesIndustriales.Api_HostAddress}}/api/productos
Content-Type: application/json

{
  "codigo": "OX-MED",
  "nombre": "Oxígeno medicinal",
  "tipoProducto": "GAS",
  "unidadMedida": "M3",
  "precioReferencia": 16.50
}

###

PUT {{GasesIndustriales.Api_HostAddress}}/api/productos/1
Content-Type: application/json

{
  "codigo": "OX-M3",
  "nombre": "Oxígeno Industrial",
  "tipoProducto": "GAS",
  "unidadMedida": "M3",
  "precioReferencia": 14.30,
  "activo": true
}

###

DELETE {{GasesIndustriales.Api_HostAddress}}/api/productos/1
Accept: application/json

###

GET {{GasesIndustriales.Api_HostAddress}}/api/cilindros
Accept: application/json

###

GET {{GasesIndustriales.Api_HostAddress}}/api/cilindros/1
Accept: application/json

###

GET {{GasesIndustriales.Api_HostAddress}}/api/dashboard/resumen
Accept: application/json
